### PR TITLE
Weather Buildings

### PR DESCRIPTION
**Pull request by Prestigexronize**
By: AJOKitty a.k.a AJOSmilodon

- Added Weather Factory
- Added Weather Good
- Added 2 pop types - Flightponies and Weatherponies
- Added production methods for Urban Centers and Wheat Farms that use Weather
- Placeholder Art Used
- Localization

### CODE REVIEW

**Comment by HaneulCheong** [comment]
I've added my bits: b9932fc

We need to make sure the AI can use the weather factories. Also, we would want to expand the wheat farm's weather PM to other agricultural buildings.

**Comment by HaneulCheong** [comment]
It also seems the amount of weather produced is too small compared to how much the farms use. The AI is building too many weather factories, which is in turn creating too many jobs for weatherponies and flightponies.

**Comment by AJOKitty** [comment]
I've got the outline for the production methods done.
Things still left to do:
- Ensure the AI makes appropriate use of weather
- Add laws to interact with weather
- Tie weather technology to the tech tree
Other long term tasks:
- Restrict Weatherpony profession to pegasi
- Acquire graphics for the buildings, production methods, and goods

**Comment by HaneulCheong** [comment]
Perfect, but I think it's time to merge this branch and add more later on, if you are fine with it.

**Comment by AJOKitty** [comment]
Current AI problem
It will build Weather Bureaus but won't use the farm production methods.

**Pull request merged**
